### Obtener todos las Categorias
GET http://localhost:3000/api/categories

### Obtener una Categoria por ID
GET http://localhost:3000/api/categories/1

### Crear una Categoria
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Electronics",
  "status": "active"
}


### Actualizar una Categoria
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "stock": 123,
    "id": 1,
    "name": "Alimentos"
}

### Eliminar una Categoria
DELETE http://localhost:3000/api/categories/3

### Baja logica de una Categoria
PATCH http://localhost:3000/api/categories/1
