### Iniciar sesion
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "enzo.sanchez.ariel@gmail.com",
    "password": "password123"
}

### Cerrar sesion
POST http://localhost:3000/api/auth/logout