### Obtener todos los Productos
GET http://localhost:3000/api/products

### Obtener un Producto por ID
GET http://localhost:3000/api/products/3

### Crear un Producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "stock":350,
    "desc": "Mayonesa Natura 550ml es una mayonesa de calidad superior, elaborada con ingredientes naturales y sin conservantes. Es ideal para acompañar tus comidas y darles un toque especial.",
    "name": "Mayonesa Natura",
    "img": "https://ardiaprod.vtexassets.com/arquivos/ids/306992/Mayonesa-Natura-250-Ml_1.jpg?v=638599324442400000",
    "prices": 200,
    "category": 1
}

### Actualizar un Producto
PUT http://localhost:3000/api/products/11
Content-Type: application/json

{
    "stock":350,
    "desc": "Mayonesa Natura 550ml es una mayonesa de calidad superior, elaborada con ingredientes naturales y sin conservantes. Es ideal para acompañar tus comidas y darles un toque especial.",
    "name": "Mayonesa Natura",
    "img": "https://ardiaprod.vtexassets.com/arquivos/ids/306992/Mayonesa-Natura-250-Ml_1.jpg?v=638599324442400000",
    "discount": 10,
    "category": 1
}

### Actualizar un Producto (PATCH)
PATCH  http://localhost:3000/api/products/3
Content-Type: application/json

{
    "stock": 123,
    "name": "RRRRRRRRRR"
}

### Eliminar un Producto
DELETE http://localhost:3000/api/products/2